apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-lens-data
  labels:
    app.kubernetes.io/part-of: agent-lens
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
