apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agent-lens
  labels:
    app: agent-lens
    app.kubernetes.io/part-of: agent-lens
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  resources:
    requests:
      cpu: "500m"
      memory: 2Gi
      ephemeral-storage: 8Gi
    limits:
      cpu: "2"
      memory: 4Gi
      ephemeral-storage: 20Gi
  output:
    to:
      kind: ImageStreamTag
      name: agent-lens:latest
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
