apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: agent-lens
  labels:
    app: agent-lens
    app.kubernetes.io/part-of: agent-lens
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: agent-lens:latest
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
